logging:
  level:
#    root: warn
    gg.trol: debug

server:
  port: 8443
  servlet:
    session:
      timeout: 30
  ssl:
    enabled: true
    key-alias: jinskeystore
    key-store: jinskeystore.pkcs12
    key-store-password: jins12
    key-password: jins12
    trust-store: jinstrust.pkcs12
    trust-store-password: jins12

spring:
  profiles: local
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
  jwt:
    secret: wlstnWkd!@#
  messages:
    basename: i18n/exception
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 958180173202-sii4epowero1eouvvjrlrnt27sikub08k.apps.googleusercontent.com
            client-secret: k0asdfag801WdcJF8k9ST_8SG9
          facebook:
            client-id: 11612612521462
            client-secret: 6578235217c5c365a98c51b02d0308ac
custom:
  oauth2:
    kakao:
      client_id: d40371283b16f07b2f05e21b09b6eb5c
      client_secret:
    naver:
      client-id: B5yvH3Zaweyawerawwe6repj4z0L
      client-secret: sArXFasdfawef
