logging:
  level:
#    root: warn
    gg.trol: debug

server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 8443

spring:
  profiles: local
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
  jwt:
    secret: wlstnWkd!@#
  messages:
    basename: i18n/exception
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 409881225357-lk43517064hccjg7d7090ubll0jrs09i.apps.googleusercontent.com
            client-secret: HmqANQ26F-whwOuNwuM7hRcK
          facebook:
            client-id: 11612612521462
            client-secret: 6578235217c5c365a98c51b02d0308ac
custom:
  oauth2:
    kakao:
      client_id: d40371283b16f07b2f05e21b09b6eb5c
      client_secret: OlLl0CrG545MYUE56LvQqKJiLSqtsMD1
    naver:
      client-id: yw75gPiM8tyt5VeaIQCn
      client-secret: 5d4a_MAmOz
