logging:
  level:
#    root: warn
    gg.trol: debug

server:
  port: 8443
  servlet:
    session:
      timeout: 30
  ssl:
    enabled: true
    key-alias: jinskeystore
    key-store: jinskeystore.pkcs12
    key-store-password: jins12
    key-password: jins12
    trust-store: jinstrust.pkcs12
    trust-store-password: jins12

spring:
  profiles: local
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
  jwt:
    secret: wlstnWkd!@#
  messages:
    basename: i18n/exception
    encoding: UTF-8
  session:
    store-type: jdbc
  social:
    kakao:
      client_id: d40371283b16f07b2f05e21b09b6eb5c # 앱생성시 받은 REST API 키
      redirect: /login/oauth/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: https://localhost:8443
